urls.py
##############################################################################
#
#    OSIS stands for Open Student Information System. It's an application
#    designed to manage the core business of higher education institutions,
#    such as universities, faculties, institutes and professional schools.
#    The core business involves the administration of students, teachers,
#    courses, programs and so on.
#
#    Copyright (C) 2015-2017 Université catholique de Louvain (http://www.uclouvain.be)
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    A copy of this license - GNU General Public License - is available
#    at the root of the source code of this program.  If not,
#    see http://www.gnu.org/licenses/.
#
##############################################################################
from django.urls import include, path, re_path

from continuing_education.forms.account import ContinuingEducationRegistrationForm
from continuing_education.views import account_activation, prospect
from continuing_education.views import (home, admission, registration, common, file)
from continuing_education.views.account_activation import (
    ContinuingEducationPasswordResetView,
    ContinuingEducationPasswordResetConfirmView,
)
from continuing_education.views.autocomplete.continuing_education_training import \
    ContinuingEducationTrainingAutocomplete

urlpatterns = [
    path('', home.formations_list, name='formations_list'),
    re_path(r'^set_lang/([A-Za-z-]+)/$', home.set_language, name='set_language'),
    path('home/', home.main_view, name='continuing_education_home'),
    re_path(r'^home/(?P<acronym>[\w]+)/$', home.main_view, name='continuing_education_home'),
    path('authentication/', include([
        path('login', common.login, name='continuing_education_login'),
        path('logout', common.log_out, name='continuing_education_logout'),
        path('logged_out', common.logged_out, name='continuing_education_logged_out')])),
    path('account/', include([
        path('register/',
            account_activation.ContinuingEducationRegistrationView.as_view(
                form_class=ContinuingEducationRegistrationForm
            ),
            name='django_registration_register'),
        path(
            'complete_account_registration/',
            account_activation.complete_account_registration,
            name='complete_account_registration'
        ),
        re_path(r'^activate/(?P<formation_id>[0-9a-f-]+)/(?P<activation_key>[-:\w]+)/$',
            account_activation.ContinuingEducationActivationView.as_view(),
            name='django_registration_activate'),
        re_path(r'^activate/(?P<activation_key>[-:\w]+)/$',
            account_activation.ContinuingEducationActivationView.as_view(),
            name='django_registration_activate'),
        path('password_reset/', ContinuingEducationPasswordResetView.as_view(), name='password_reset'),
        re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,32})/$',
            ContinuingEducationPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
        path('', include('django_registration.backends.activation.urls'))])),
    re_path(r'^admission_new/', admission.admission_form, name='admission_new'),
    re_path(r'^admission_edit/(?P<admission_uuid>[0-9a-f-]+)$', admission.admission_form, name='admission_edit'),
    re_path(r'^admission_detail/(?P<admission_uuid>[0-9a-f-]+)$', admission.admission_detail, name='admission_detail'),
    re_path(r'^admission_submit/', admission.admission_submit, name='admission_submit'),
    re_path(
        r'^registration_edit/(?P<admission_uuid>[0-9a-f-]+)$',
        registration.registration_edit,
        name='registration_edit'
    ),
    re_path(r'^registration_detail/(?P<admission_uuid>[0-9a-f-]+)$', registration.registration_detail,
        name='registration_detail'),
    re_path(r'^registration_pdf/(?P<admission_uuid>[0-9a-f-]+)$', registration.generate_pdf_registration,
        name='registration_pdf'),
    re_path(r'^registration_submit/', registration.registration_submit, name='registration_submit'),
    re_path(
        r'^download_file/(?P<file_uuid>[0-9a-f-]+)/(?P<admission_uuid>[0-9a-f-]+)',
        file.download_file,
        name="download_file"
    ),
    re_path(
        r'^remove_file/(?P<file_uuid>[0-9a-f-]+)/(?P<admission_uuid>[0-9a-f-]+)',
        file.remove_file,
        name="remove_file"
    ),
    re_path(
        r'^upload_file/(?P<admission_uuid>[0-9a-f-]+)',
        file.upload_file,
        name="upload_file"
    ),
    re_path(r'^prospect_form/(?P<acronym>[\w]+)/$', prospect.prospect_form, name='prospect_form'),
    path('prospect_form/', prospect.prospect_form, name='prospect_form'),
    path(
        'cetraining-autocomplete/',
        ContinuingEducationTrainingAutocomplete.as_view(),
        name='cetraining-autocomplete',
    ),
    re_path(r'^ajax/formation/', admission.get_formation_information, name='get_formation_information')
]

forms/admission.py
from dal import autocomplete
from django import forms
from django.core.validators import RegexValidator
from django.forms import ChoiceField, Form
from django.utils.translation import gettext_lazy as _

from continuing_education.models.enums import enums, admission_state_choices

phone_regex = RegexValidator(
    regex=r'^(?P<prefix_intro>\+|0{1,2})\d{7,15}$',
    message=_("Phone number must start with 0 or 00 or '+' followed by at least 7 digits and up to 15 digits.")
)


class AdmissionForm(Form):
    formation = autocomplete.Select2ListCreateChoiceField(
        widget=autocomplete.ListSelect2(url='cetraining-autocomplete'),
        required=True,
    )

    state = ChoiceField(
        choices=admission_state_choices.STUDENT_STATE_CHOICES,
        required=False
    )
    citizenship = autocomplete.Select2ListCreateChoiceField(
        widget=autocomplete.ListSelect2(url='country-autocomplete'),
        required=False,
        label=_("Citizenship")
    )
    high_school_diploma = forms.TypedChoiceField(
        coerce=lambda x: x == 'True',
        required=False,
        choices=enums.YES_NO_CHOICES,
        label=_("High school diploma")
    )

    person_information = forms.CharField(
        required=False,
    )

    # Contact
    address = forms.CharField(
        required=False,
    )

    phone_mobile = forms.CharField(
        required=False,
        label=_("Phone mobile"),
    )

    email = forms.EmailField(
        max_length=255,
        required=True,
        label=_("Additional email")
    )

    # Education

    high_school_graduation_year = forms.IntegerField(
        required=False,
        label=_("High school graduation year")
    )
    last_degree_level = forms.CharField(
        max_length=50,
        required=False,
        label=_("Last degree level")
    )
    last_degree_field = forms.CharField(
        max_length=50,
        required=False,
        label=_("Last degree field")
    )
    last_degree_institution = forms.CharField(
        max_length=50,
        required=False,
        label=_("Last degree institution")
    )
    last_degree_graduation_year = forms.IntegerField(
        required=False,
        label=_("Last degree graduation year")
    )
    other_educational_background = forms.CharField(
        widget=forms.Textarea,
        required=False,
        label=_("Other educational background")
    )

    # Professional Background
    professional_status = forms.ChoiceField(
        required=False,
        choices=enums.STATUS_CHOICES,
        label=_("Professional status")
    )
    current_occupation = forms.CharField(
        max_length=50,
        required=False,
        label=_("Current occupation")
    )
    current_employer = forms.CharField(
        max_length=50,
        required=False,
        label=_("Current employer")
    )
    activity_sector = forms.ChoiceField(
        required=False,
        choices=enums.SECTOR_CHOICES,
        label=_("Activity sector")
    )
    past_professional_activities = forms.CharField(
        widget=forms.Textarea,
        required=False,
        label=_("Past professional activities")
    )

    # Motivation
    motivation = forms.CharField(
        widget=forms.Textarea,
        required=False,
        label=_("Motivation")
    )
    professional_personal_interests = forms.CharField(
        widget=forms.Textarea,
        required=False,
        label=_("Professional and personal interests")
    )

    # Awareness
    awareness_ucl_website = forms.BooleanField(
        initial=False,
        required=False,
        label=_("By UCLouvain website")
    )
    awareness_formation_website = forms.BooleanField(
        initial=False,
        required=False,
        label=_("By formation website")
    )
    awareness_press = forms.BooleanField(
        initial=False,
        required=False,
        label=_("By press")
    )
    awareness_facebook = forms.BooleanField(
        initial=False,
        required=False,
        label=_("By Facebook")
    )
    awareness_linkedin = forms.BooleanField(
        initial=False,
        required=False,
        label=_("By LinkedIn")
    )
    awareness_customized_mail = forms.BooleanField(
        initial=False,
        required=False,
        label=_("By customized mail")
    )
    awareness_emailing = forms.BooleanField(
        initial=False,
        required=False,
        label=_("By emailing")
    )
    awareness_word_of_mouth = forms.BooleanField(
        initial=False,
        required=False,
        label=_("By word of mouth")
    )
    awareness_friends = forms.BooleanField(
        initial=False,
        required=False,
        label=_("By friends")
    )
    awareness_former_students = forms.BooleanField(
        initial=False,
        required=False,
        label=_("By former students")
    )
    awareness_moocs = forms.BooleanField(
        initial=False,
        required=False,
        label=_("By Moocs")
    )
    awareness_other = forms.CharField(
        max_length=100,
        required=False,
        label=_("Other")
    )

    # State
    state_reason = forms.CharField(
        widget=forms.Textarea,
        required=False,
        label=_("State reason")
    )

    additional_information = forms.CharField(
        widget=forms.Textarea,
        required=False,
        label=_("Additional Information")
    )

    def clean_phone_mobile(self):
        return self.cleaned_data['phone_mobile'].replace(' ', '')

    def __init__(self, *args, **kwargs):
        formation = kwargs.pop('formation', None)
        user = kwargs.pop('user', None)
        self.initial = kwargs.get('data', kwargs.get('initial'))
        super(AdmissionForm, self).__init__(*args, **kwargs)
        if formation and formation['active']:
            self.initial['formation'] = (formation['education_group']['acronym'], _format_training_title(formation))
            self.fields['formation'].choices = [self.initial['formation']]
        if self.initial:
            self._set_initial_fields()
        self.fields['additional_information'].widget.attrs['placeholder'] = _(
            "Write down here the answers to further questions related to the chosen training"
        )
        self.fields['email'].initial = user.email if user else ''

    def _set_initial_fields(self):
        fields_to_set = [('citizenship', 'name', 'iso_code')]
        for field, attribute, slug in fields_to_set:
            if self.initial.get(field):
                if isinstance(attribute, str):
                    self.initial[field] = (
                        self.initial[field][slug],
                        self.initial[field][attribute]
                    )
                self.fields[field].choices = [self.initial[field]]


class StrictAdmissionForm(AdmissionForm):
    phone_mobile = forms.CharField(
        validators=[phone_regex],
        required=False,
        label=_("Phone mobile"),
        widget=forms.TextInput(attrs={'placeholder': '0474123456 - 0032474123456 - +32474123456'})
    )

    def __init__(self, data, **kwargs):
        super().__init__(data=data, **kwargs)

        required_fields = [
            'citizenship',
            'phone_mobile',
            'high_school_diploma',
            'last_degree_level',
            'last_degree_field',
            'last_degree_institution',
            'last_degree_graduation_year',
            'professional_status',
            'current_occupation',
            'current_employer',
            'activity_sector',
            'motivation',
            'professional_personal_interests',
            'formation'
        ]

        formation_info = data['formation'] if type(data['formation']) is dict else data.get('formation_info', None)

        if formation_info and _has_required_additional_information(formation_info):
            required_fields.append('additional_information')

        for required_field in required_fields:
            self.fields[required_field].required = True


def _has_required_additional_information(formation):
    return 'additional_information_label' in formation.keys() and formation['additional_information_label']


def _format_training_title(training):
    return "{} - {}".format(training['education_group']['acronym'], training['education_group']['title'])

forms/prospect.py
from dal import autocomplete
from django import forms
from django.forms import Form
from django.utils.translation import gettext_lazy as _


class ProspectForm(Form):
    first_name = forms.CharField(
        required=True,
        label=_("First name"),
        max_length=20,
    )

    name = forms.CharField(
        required=True,
        label=_("Name"),
        max_length=40,
    )

    postal_code = forms.CharField(
        required=True,
        label=_("Postal code")
    )

    city = forms.CharField(
        required=True,
        label=_("City")
    )

    email = forms.EmailField(
        required=True,
        label=_("Email")
    )

    phone_number = forms.CharField(
        required=True,
        label=_("Phone number")
    )

    formation = autocomplete.Select2ListCreateChoiceField(
        widget=autocomplete.ListSelect2(url='cetraining-autocomplete'),
        required=True,
        label=_("Formation")
    )

    def __init__(self, *args, **kwargs):
        formation = kwargs.pop('ce_training', None)
        super(ProspectForm, self).__init__(*args, **kwargs)
        if formation:
            self.fields['formation'] = forms.CharField(
                disabled=True
            )
            self.initial['formation'] = formation['education_group']['acronym']

    class Meta:
        fields = [
            'name',
            'first_name',
            'postal_code',
            'city',
            'email',
            'phone_number',
            'formation',
        ]

views/prospect.py
from django.shortcuts import render
from django.utils.translation import gettext_lazy as _

from continuing_education.forms.prospect import ProspectForm
from continuing_education.views import api
from continuing_education.views.api import post_prospect
from continuing_education.views.common import display_success_messages


def prospect_form(request, acronym=None):
    cet = None
    if acronym:
        cet = api.get_continuing_education_training(request, acronym)
    form = ProspectForm(request.POST or None, ce_training=cet)

    if form.is_valid():
        prospect = {
            'name': request.POST.get('name'),
            'first_name': request.POST.get('first_name'),
            'city': request.POST.get('city'),
            'postal_code': request.POST.get('postal_code'),
            'email': request.POST.get('email'),
            'formation': cet['uuid'],
            'phone_number': request.POST.get('phone_number')
        }
        data, response_status_code = post_prospect(request, prospect)
        if response_status_code == 201:
            display_success_messages(request, _("Your form has been correctly sent."))
    return render(request, 'prospect_form.html', locals())

templates/registration_detail.html
{% extends "continuing_education_layout.html" %}
{% load static %}
{% load i18n %}
{% load bootstrap3 %}

{% comment "License" %}
    * OSIS stands for Open Student Information System. It's an application
    * designed to manage the core business of higher education institutions,
    * such as universities, faculties, institutes and professional schools.
    * The core business involves the administration of students, teachers,
    * courses, programs and so on.
    *
    * Copyright (C) 2015-2022 Université catholique de Louvain (http://www.uclouvain.be)
    *
    * This program is free software: you can redistribute it and/or modify
    * it under the terms of the GNU General Public License as published by
    * the Free Software Foundation, either version 3 of the License, or
    * (at your option) any later version.
    *
    * This program is distributed in the hope that it will be useful,
    * but WITHOUT ANY WARRANTY; without even the implied warranty of
    * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    * GNU General Public License for more details.
    *
    * A copy of this license - GNU General Public License - is available
    * at the root of the source code of this program.  If not,
    * see http://www.gnu.org/licenses/.
{% endcomment %}

{% block breadcrumb %}
    <li><a href="{% url 'continuing_education_home' %}">{% trans 'Continuing Education' %}</a></li>
    <li><a class="text-capitalize" href="{% url 'continuing_education_home' %}">{% trans 'Student' %}</a></li>
    <li class="active">{% trans 'Registration' %}</li>
{% endblock %}

{% block content %}
    <div class="page-header">
        {% if registration_is_submittable and is_accepted %}
            <form id="form" method="POST" class="post-form" action="{% url 'registration_submit' %}">
                {% csrf_token %}
                <a class="btn btn-primary pull-right" data-toggle="modal" data-target="#submit_confirmation_modal"
                   id="btn_registration_finalize">
                    <span class="glyphicon glyphicon-save"
                          aria-hidden="true"></span> {% trans 'Submit' context "admission" %}
                </a>
                <input type="hidden" name="registration_uuid" value="{{ admission.uuid }}"/>
                {% include "fragment/submit_confirmation_modal.html" %}
            </form>
        {% endif %}
        {% if is_accepted %}
            <a class="btn btn-default btn-space pull-right"
               href="{% url 'registration_edit' admission_uuid=admission.uuid %}">
                <span class="glyphicon glyphicon-pencil"
                      aria-hidden="true"></span> {% trans 'Complete my application'%}
            </a>
            <span class="admission-detail-state admission-detail-state-draft btn-space pull-right">
                {% trans "Not submitted" %}
            </span>
        {% else %}
            <span class="admission-detail-state admission-detail-state-{{ admission.state|lower|slugify }} btn-space pull-right">
                {% trans admission.state %}
            </span>
        {% endif %}
        {% if is_registration_submitted %}
            <a class="btn btn-success btn-space pull-right"
               href="{% url 'registration_pdf' admission_uuid=admission_uuid %}">
                <span class="glyphicon glyphicon-save-file" aria-hidden="true"></span> {% trans 'Generate PDF' %}
            </a>
        {% endif %}
        <h2>{% trans 'Registration' %}</h2>
        <h4>{{ admission.formation.education_group.acronym | default:"-" }} -
            {{ admission.formation.education_group.title | default:"-" }}</h4>
    </div>
    {% include 'template_messages.html' %}
    <div class="panel panel-default">
    <ul id="tabs" class="nav nav-tabs">
        <li role="presentation" class="active"><a href="#informations" role="tab"
                                                  data-toggle="tab">{% trans 'Informations' %}</a></li>
        <li role="presentation"><a href="#documents" role="tab" data-toggle="tab">{% trans 'Documents' %}</a></li>
    </ul>
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="informations">
            <div class="panel panel-default">
                {% csrf_token %}
                <div class="panel-heading">{% trans 'Identification' %}</div>
                <div class="panel panel-body">
                    <div class="row form-group">
                        <div class="col-md-3">{% bootstrap_label _("First name") %} <br/>
                            {{ admission.person_information.person.first_name | default:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Last name") %} <br/>
                            {{ admission.person_information.person.last_name | default:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Gender") %} <br/>
                            {{ admission.person_information.person.gender | default:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Citizenship") %}
                            <br/>{{ admission.citizenship.nationality | upper | default:"-" }}</div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">{% bootstrap_label _("Birth date") %} <br/>
                            {{ admission.person_information.birth_date | default:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Birth location") %} <br/>
                            {{ admission.person_information.birth_location | upper | default:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Birth country") %} <br/>
                            {{ admission.person_information.birth_country.name| upper | default:"-" }} </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">{% bootstrap_label _("National registry number") %} <br/>
                            {{ admission.national_registry_number | default_if_none:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("ID card number") %} <br/>
                            {{ admission.id_card_number | default_if_none:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Passport number") %} <br/>
                            {{ admission.passport_number | default_if_none:"-" }} </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">{% bootstrap_label _("Marital status") %} <br/>
                            {{ admission.marital_status_text | default_if_none:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Spouse name") %} <br/>
                            {{ admission.spouse_name | default_if_none:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Children number") %} <br/>
                            {{ admission.children_number | default_if_none:"-" }} </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-6">{% bootstrap_label _("Previous UCLouvain registration") %}
                            <br/> {{ admission.previous_ucl_registration | yesno }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Previous NOMA") %} <br/>
                            {{ admission.previous_noma | default_if_none:"-" }} </div>
                    </div>
                    {% if is_accepted and  admission.condition_of_acceptance %}
                        <div class="row form-group">
                            <div class="col-md-12">{% bootstrap_label _("Conditionally accepted") %}
                                <br/> {{ admission.condition_of_acceptance }} </div>

                        </div>
                    {% endif %}
                </div>

                <div class="panel-heading">{% trans 'Billing' %}</div>
                <div class="panel panel-body">
                    <div class="row form-group">
                        <div class="col-md-3">{% bootstrap_label _("Registration type") %} <br/>
                            {{ admission.registration_type_text | default_if_none:"-" }} </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">{% bootstrap_label _("Location") %} <br/>
                            {{ admission.billing_address.location | default_if_none:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Postal code") %} <br/>
                            {{ admission.billing_address.postal_code | default_if_none:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("City") %} <br/>
                            {{ admission.billing_address.city | upper | default_if_none:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Country") %} <br/>
                            {{ admission.billing_address.country.name | upper | default_if_none:"-" }} </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-3">{% bootstrap_label _("Head office name") %} <br/>
                            {{ admission.head_office_name | default_if_none:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Company number") %} <br/>
                            {{ admission.company_number | default_if_none:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("VAT number") %} <br/>
                            {{ admission.vat_number | default_if_none:"-" }} </div>
                    </div>
                </div>

                <div class="panel-heading">{% trans 'Post' %}</div>
                <div class="panel panel-body">
                    <div class="row form-group">
                        <div class="col-md-3">{% bootstrap_label _("Location") %} <br/>
                            {{ admission.residence_address.location | default_if_none:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Postal code") %} <br/>
                            {{ admission.residence_address.postal_code | default_if_none:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("City") %} <br/>
                            {{ admission.residence_address.city | upper | default_if_none:"-" }} </div>
                        <div class="col-md-3">{% bootstrap_label _("Country") %} <br/>
                            {{ admission.residence_address.country.name | upper | default_if_none:"-" }} </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-4">{% bootstrap_label _("Residence phone") %} <br/>
                            {{ admission.residence_phone | default_if_none:"-" }} </div>
                    </div>
                </div>
            </div>
        </div>
        <div role="tabpanel" class="tab-pane" id="documents">
            <div class="panel-body">
                {% include 'fragment/files_panel.html' %}
            </div>
        </div>
    </div>
    {% include 'fragment/registration_instructions_modal.html' %}
{% endblock %}


{% block script %}
    <script>
        $('.high_school_graduation_year').hide();
        $('#id_high_school_diploma').on('change', function () {
            $('.high_school_graduation_year').toggle($(this).find(":selected").val());
        });

        $('#tabs a').click(function (e) {
            e.preventDefault();
            $(this).tab('show');
        });

        var anchor = location.hash;
        $('#tabs a[href="' + anchor + '"]').tab('show');

        $('#customFile').change(function (e) {
            $('#custom-file-label').text(this.files[0].name);
            $('#btn-upload').removeAttr("disabled")
        });
        
        $("#show-instructions-button").click(function(){
            $("#instructions_modal").modal('show');
        });

        $( ".conditions_checkboxes" ).change(function(e) {
            let allBoxesChecked = $(".conditions_checkboxes:checked").length === 3;
            $('#btn_finalize').prop('disabled', !allBoxesChecked);
        });

    </script>
{% endblock %}